import React, { useEffect, useState, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getIncrementStory, getIncrementStories } from '../../services/incrementStoryService';
import { type IncrementStory } from '../../types/incrementStory';
import { format } from 'date-fns';
import { ArrowLeft, Download, Award, TrendingUp, AlertCircle, CheckCircle2, Star } from 'lucide-react';
import { motion } from 'framer-motion';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const IncrementStoryDetail: React.FC = () => {
  const { cycleId } = useParams<{ cycleId: string }>();
  const { user } = useAuth();
  const [story, setStory] = useState<IncrementStory | null>(null);
  const [allStories, setAllStories] = useState<IncrementStory[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const pdfRef = useRef<HTMLDivElement>(null);
  const animatedRef = useRef(false);

  useEffect(() => {
    if (!user?.uid || !cycleId) return;

    const fetchStory = async () => {
      const data = await getIncrementStory(user.uid, cycleId);
      setStory(data);
      setLoading(false);
      // Mark for animation
      setTimeout(() => animatedRef.current = true, 2000);
    };

    fetchStory();

    const unsubscribe = getIncrementStories(user.uid, (data) => {
      // Sort ascending for chart
      const sorted = [...data].sort((a, b) => a.completedAt.toMillis() - b.completedAt.toMillis());
      setAllStories(sorted);
    });

    return () => unsubscribe();
  }, [user, cycleId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[60vh]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500"></div>
      </div>
    );
  }

  if (!story) {
    return (
      <div className="max-w-4xl mx-auto text-center py-20 font-brand">
        <h2 className="text-2xl font-bold text-slate-700">Story not found</h2>
        <Link to="/increments" className="text-emerald-500 hover:underline mt-4 inline-block">← Back to My Increments</Link>
      </div>
    );
  }

  const handleDownloadPDF = async () => {
    if (!pdfRef.current || !user) return;
    setDownloading(true);
    try {
      const canvas = await html2canvas(pdfRef.current, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#f8fafc' // merit-bg
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      // Header
      pdf.setFillColor(15, 23, 42); // merit-navy
      pdf.rect(0, 0, pdfWidth, 20, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('MeritCyc', 10, 14);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Increment Story: ${story.cycleName} - ${user.name}`, 100, 14);

      // Content
      pdf.addImage(imgData, 'PNG', 0, 25, pdfWidth, pdfHeight);

      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated by MeritCyc on ${format(new Date(), 'MMM d, yyyy')}`, 10, pdf.internal.pageSize.getHeight() - 10);

      pdf.save(`increment-story-${story.cycleName.replace(/\s+/g, '-').toLowerCase()}-${user.name?.replace(/\s+/g, '-').toLowerCase()}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setDownloading(false);
    }
  };

  const chartData = allStories.map(s => ({
    name: s.cycleName.substring(0, 10) + (s.cycleName.length > 10 ? '...' : ''),
    score: s.score,
    tier: s.tierName,
    increment: s.incrementPercent,
    isCurrent: s.cycleId === story.cycleId
  }));

  const getGradientForTier = () => {
    if (story.score >= 90) return 'from-blue-900 to-blue-800';
    if (story.score >= 75) return 'from-slate-900 to-emerald-900';
    if (story.score >= 50) return 'from-slate-900 to-slate-800';
    return 'from-slate-900 to-slate-800';
  };

  const getPerformanceBadge = (perf: string) => {
    switch (perf) {
      case 'excellent': return { label: 'Excellent', className: 'bg-blue-100 text-blue-700' };
      case 'good': return { label: 'Good', className: 'bg-emerald-100 text-emerald-700' };
      case 'average': return { label: 'Average', className: 'bg-amber-100 text-amber-700' };
      case 'needs_improvement': return { label: 'Needs Improvement', className: 'bg-red-100 text-red-700' };
      default: return { label: 'Unknown', className: 'bg-slate-100 text-slate-700' };
    }
  };

  const getScoreDisplay = (item: { measurementType: string, rawScore: number }) => {
    if (item.measurementType === 'boolean') return item.rawScore === 1 ? 'Yes ✓' : 'No ✗';
    if (item.measurementType === 'rating') return `${item.rawScore} ★`;
    if (item.measurementType === 'percentage') return `${item.rawScore}%`;
    return `${item.rawScore}`;
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 font-brand pb-12">

      {/* HEADER */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <Link to="/increments" className="text-slate-500 hover:text-merit-emerald flex items-center gap-2 text-sm font-medium mb-3">
            <ArrowLeft className="w-4 h-4" /> Back to My Increments
          </Link>
          <h1 className="text-3xl font-bold text-merit-navy">{story.cycleName}</h1>
          <p className="text-slate-500 mt-1">
            {format(story.cycleStartDate.toDate(), 'MMMM d')} – {format(story.cycleEndDate.toDate(), 'MMMM d, yyyy')}
          </p>
        </div>
        <div className="text-right flex flex-col items-end">
          <p className="text-sm font-medium text-slate-500 bg-slate-100 px-3 py-1 rounded-full inline-block">
            Results published on {format(story.completedAt.toDate(), 'MMM d, yyyy')}
          </p>
        </div>
      </div>

      <div ref={pdfRef} id="story-export-content" className="space-y-8 bg-merit-bg pb-4">

        {/* HERO RESULT CARD */}
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          className={`rounded-2xl p-8 sm:p-12 text-center text-white relative overflow-hidden shadow-xl bg-gradient-to-br ${getGradientForTier()}`}
        >
          <div className="absolute top-0 right-0 p-12 opacity-10 pointer-events-none">
            <Award className="w-64 h-64 -mt-20 -mr-20" />
          </div>

          <div className="relative z-10">
            <p className="text-sm font-bold text-white/60 uppercase tracking-widest mb-4">Your Result</p>
            <div className="flex items-end justify-center gap-2 mb-2">
              <Counter target={story.score} />
            </div>
            <p className="text-lg font-medium text-white/80 mb-6">out of 100</p>

            <div className="inline-block px-6 py-2 rounded-full text-lg font-bold shadow-lg" style={{ backgroundColor: story.tierColor, color: '#fff' }}>
              {story.tierName}
            </div>

            <div className="mt-8 pt-8 border-t border-white/20">
              <h2 className="text-3xl sm:text-4xl font-black mb-2" style={{ color: story.tierColor }}>
                +{story.incrementPercent.toFixed(1)}% Salary Increment
              </h2>
              {story.incrementAmount && (
                <p className="text-xl text-white/80 font-medium">
                  = +{story.currency || 'LKR'} {story.incrementAmount.toLocaleString()} per month
                </p>
              )}
            </div>

            <div className="mt-6">
              {story.isFirstCycle ? (
                <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 text-white text-sm font-bold border border-white/20">
                  <Star className="w-4 h-4 text-amber-400" /> Your first cycle!
                </span>
              ) : story.previousScore !== undefined ? (
                <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 text-white text-sm font-bold border border-white/20">
                  {story.score >= story.previousScore ? <TrendingUp className="w-4 h-4 text-emerald-400" /> : <TrendingUp className="w-4 h-4 text-red-400 transform rotate-180" />}
                  {story.score >= story.previousScore ? '+' : ''}{(story.score - story.previousScore).toFixed(1)} points from last cycle
                </span>
              ) : null}
            </div>
          </div>
        </motion.div>

        {/* SCORE BREAKDOWN SECTION */}
        <div>
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-merit-navy">How Your Score Was Calculated</h2>
            <p className="text-slate-500 mt-1">Your final score is the weighted sum of all criteria below</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            {story.scoreBreakdown.sort((a, b) => b.weight - a.weight).map((item) => {
              const badge = getPerformanceBadge(item.performance);
              return (
                <div key={item.criteriaId} className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h3 className="font-bold text-merit-navy text-lg">{item.criteriaName}</h3>
                      <div className="flex gap-2 mt-2">
                        <span className="text-xs font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded">
                          {item.weight}% weight
                        </span>
                        <span className="text-xs font-medium bg-slate-50 border border-slate-200 text-slate-500 px-2 py-0.5 rounded capitalize">
                          {item.measurementType} data
                        </span>
                      </div>
                    </div>
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-md ${badge.className}`}>
                      {badge.label}
                    </span>
                  </div>

                  <div className="flex justify-between items-end mb-2 mt-6">
                    <div>
                      <div className="text-3xl font-black text-slate-800">{getScoreDisplay(item)}</div>
                      <div className="text-xs font-medium text-slate-400 mt-1">= {item.normalizedScore}/100 normalized</div>
                    </div>
                    <div className="text-right">
                      <div className="text-lg font-bold text-emerald-600">+{item.weightedScore.toFixed(1)} pts</div>
                      <div className="text-xs text-slate-400">contribution</div>
                    </div>
                  </div>

                  <div className="w-full bg-slate-100 rounded-full h-2 mt-3">
                    <motion.div
                      className="h-2 rounded-full"
                      style={{ backgroundColor: getPerformanceColor(item.performance) }}
                      initial={{ width: 0 }}
                      animate={{ width: `${item.normalizedScore}%` }}
                      transition={{ duration: 1 }}
                    ></motion.div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="bg-slate-900 text-white rounded-xl p-6 flex flex-col sm:flex-row items-center justify-between shadow-lg">
            <div className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-2 sm:mb-0">Final Equation</div>
            <div className="flex flex-wrap items-center justify-center gap-2 text-lg font-medium">
              {story.scoreBreakdown.map((item, i) => (
                <React.Fragment key={item.criteriaId}>
                  <span>{item.weightedScore.toFixed(1)}</span>
                  {i < story.scoreBreakdown.length - 1 && <span className="text-slate-500">+</span>}
                </React.Fragment>
              ))}
              <span className="text-slate-500 mx-2">=</span>
              <span className="text-2xl font-black text-emerald-400">{story.score.toFixed(1)} / 100</span>
            </div>
          </div>
        </div>

        {/* TIER EXPLANATION SECTION */}
        <div>
          <h2 className="text-2xl font-bold text-merit-navy mb-6">What This Means</h2>
          <div className="bg-white border-2 rounded-xl p-8 shadow-sm flex flex-col md:flex-row gap-8 items-center" style={{ borderColor: `${story.tierColor}40` }}>
            <div className="md:w-1/3 text-center border-b md:border-b-0 md:border-r border-slate-200 pb-6 md:pb-0 md:pr-8">
              <div className="text-4xl font-black mb-2" style={{ color: story.tierColor }}>{story.tierName}</div>
              <div className="text-sm text-slate-500 font-medium">Performance Tier</div>
            </div>
            <div className="md:w-2/3 space-y-4 text-slate-600">
              <p className="text-lg">
                <strong className="text-merit-navy">Congratulations!</strong> Your score of {story.score.toFixed(1)} places you in the <strong style={{ color: story.tierColor }}>{story.tierName}</strong> tier.
                This reflects your overall performance across all evaluated criteria.
              </p>
              <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 flex flex-col sm:flex-row gap-4 justify-between">
                <div>
                  <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Your Increment</div>
                  <div className="font-bold text-merit-navy">{story.incrementPercent.toFixed(1)}%</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* RECOMMENDATIONS SECTION */}
        <div>
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-merit-navy">How to Improve Next Cycle</h2>
            <p className="text-slate-500 mt-1">Personalized suggestions based on your performance</p>
          </div>

          {story.recommendations.length === 0 ? (
            <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-6 flex items-start gap-4">
              <CheckCircle2 className="w-8 h-8 text-emerald-500 flex-shrink-0 mt-1" />
              <div>
                <h3 className="font-bold text-emerald-900 text-lg">Excellent work!</h3>
                <p className="text-emerald-700 mt-1">Keep maintaining your high performance across all criteria. There are no specific areas flagged for urgent improvement.</p>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              {story.recommendations.sort((a, b) => {
                const pMap: Record<string, number> = { high: 3, medium: 2, low: 1 };
                return (pMap[b.priority] || 0) - (pMap[a.priority] || 0);
              }).map((rec) => (
                <div key={rec.criteriaId} className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm flex gap-4">
                  <div className="mt-1">
                    {rec.priority === 'high' ? <AlertCircle className="w-6 h-6 text-red-500" /> :
                     rec.priority === 'medium' ? <AlertCircle className="w-6 h-6 text-amber-500" /> :
                     <TrendingUp className="w-6 h-6 text-slate-400" />}
                  </div>
                  <div className="flex-1">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="font-bold text-merit-navy">{rec.criteriaName}</h3>
                      <span className={`text-xs font-bold px-2 py-0.5 rounded ${
                        rec.priority === 'high' ? 'bg-red-50 text-red-600' :
                        rec.priority === 'medium' ? 'bg-amber-50 text-amber-600' :
                        'bg-slate-100 text-slate-600'
                      }`}>
                        {rec.priority} priority
                      </span>
                    </div>
                    <p className="text-slate-600 text-sm mb-4">{rec.suggestion}</p>

                    <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 flex items-center justify-between">
                      <div className="text-xs font-bold text-slate-500">Current: <span className="text-slate-800">{rec.currentScore.toFixed(0)}</span></div>
                      <div className="flex-1 px-4">
                        <div className="relative h-2 bg-slate-200 rounded-full w-full">
                          <div className="absolute left-0 top-0 h-full bg-slate-400 rounded-full" style={{ width: `${rec.currentScore}%` }}></div>
                          <div className="absolute top-0 h-full bg-emerald-400 rounded-r-full" style={{ left: `${rec.currentScore}%`, width: `${Math.max(0, rec.targetScore - rec.currentScore)}%` }}></div>
                        </div>
                      </div>
                      <div className="text-xs font-bold text-emerald-600">Target: {rec.targetScore.toFixed(0)}</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* COMPARISON SECTION */}
        {!story.isFirstCycle && chartData.length > 1 && (
          <div>
            <h2 className="text-2xl font-bold text-merit-navy mb-6">Your Progress Over Time</h2>
            <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm h-80">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis dataKey="name" tick={{ fill: '#64748b', fontSize: 12 }} axisLine={false} tickLine={false} />
                  <YAxis domain={[0, 100]} tick={{ fill: '#64748b', fontSize: 12 }} axisLine={false} tickLine={false} />
                  <Tooltip
                    contentStyle={{ borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    formatter={(value: any, name: any) => [value, name === 'score' ? 'Score' : name]}
                  />
                  <Line
                    type="monotone"
                    dataKey="score"
                    stroke="#10b981"
                    strokeWidth={3}
                    dot={(props: { cx?: number; cy?: number; payload?: { name: string; isCurrent: boolean } }) => {
                      const { cx, cy, payload } = props;
                      if (!cx || !cy || !payload) return <></>;
                      if (payload.isCurrent) {
                        return <circle cx={cx} cy={cy} r={6} fill="#10b981" stroke="#fff" strokeWidth={2} key={payload.name} />;
                      }
                      return <circle cx={cx} cy={cy} r={4} fill="#64748b" stroke="#fff" strokeWidth={2} key={payload.name} />;
                    }}
                    activeDot={{ r: 8, fill: '#10b981', stroke: '#fff', strokeWidth: 2 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}

      </div>

      {/* SHARE / DOWNLOAD SECTION */}
      <div className="flex justify-center pt-8 border-t border-slate-200">
        <button
          onClick={handleDownloadPDF}
          disabled={downloading}
          className="flex items-center gap-2 px-8 py-3 bg-white border border-slate-300 text-merit-navy font-bold rounded-xl hover:bg-slate-50 transition-colors shadow-sm disabled:opacity-50"
        >
          {downloading ? (
            <><div className="animate-spin w-5 h-5 border-2 border-slate-400 border-t-transparent rounded-full"></div> Generating PDF...</>
          ) : (
            <><Download className="w-5 h-5" /> Download as PDF</>
          )}
        </button>
      </div>

    </div>
  );
};

const getPerformanceColor = (perf: string) => {
  switch (perf) {
    case 'excellent': return '#3b82f6';
    case 'good': return '#10b981';
    case 'average': return '#f59e0b';
    case 'needs_improvement': return '#ef4444';
    default: return '#94a3b8';
  }
};

const Counter = ({ target }: { target: number }) => {
  const [count, setCount] = useState(0);

  useEffect(() => {
    let start = 0;
    const end = target;
    const duration = 1500;
    const increment = end / (duration / 16);

    const timer = setInterval(() => {
      start += increment;
      if (start >= end) {
        setCount(end);
        clearInterval(timer);
      } else {
        setCount(start);
      }
    }, 16);

    return () => clearInterval(timer);
  }, [target]);

  return <span className="text-8xl font-black tracking-tighter" style={{ lineHeight: 1 }}>{count.toFixed(1)}</span>;
};

export default IncrementStoryDetail;